[package]
name = "syncr"
version = "0.1.0"
authors = ["Szilard Hajba <szilu@symbion.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "1.0"
async-std = "1.6"
base64 = "0.13"
clap = "2.33"
futures = "0.3"
glob = "0.3"
lmdb = "0.8"
memmap = "0.7"
rollsum = "0.2"
sha = "1.0"

[profile.release]
opt-level = 3
debug = 0
debug-assertions = false
lto = true
incremental = false
